### ISSUE TITLE
Training omnipose with existing cell data fails

### ISSUE THREAD

**Issue by michaels10** [kevinjohncutler/omnipose#33] opened 2023-01-11 02:40 UTC
Hello again,
I'm attempting to train omnipose on some existing data, but it is producing an exception. I suspect that I may be preparing data incorrectly, but am not entirely sure what the issue is.

Steps to reproduce:
1. Make a folder called `training-data`, into which you can place the following sample images: [omnipose-error.zip](https://github.com/kevinjohncutler/omnipose/files/10388419/omnipose-error.zip)
2. Run:`python -m cellpose --train --dir training-data --pretrained_model cyto --chan 0`

You should see the following error:
```
Traceback (most recent call last):
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/__main__.py", line 506, in <module>
    main()
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/__main__.py", line 455, in main
    model = models.CellposeModel(device=device,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/models.py", line 445, in __init__
    super().__init__(gpu=gpu, pretrained_model=False,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/core.py", line 165, in __init__
    self.net = CPnet(self.nbase, 
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/resnet_torch.py", line 241, in __init__
    self.output = batchconv(nbaseup[0], nout, 1, self.dim)
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/resnet_torch.py", line 35, in batchconv
    nn.Conv2d(in_channels, out_channels, sz, padding=sz//2),
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 444, in __init__
    super(Conv2d, self).__init__(
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 85, in __init__
    if out_channels % groups != 0:
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```

**Additional details:**
M1 Mac Studio
python version 3.10.8.
Omnipose installed via the git repo

**Comment by kevinjohncutler** [comment] 2023-01-11 02:47
@michaels10 I was just about to sit down and try training Omnipose on an Apple Silicon machine myself to see if the Mac Studio is a viable option for me (128GB of unified memory available to the GPU would be amazing). I'll first test your images on my linux machine and see if I can reproduce your error on it and then my macbook.

**Comment by michaels10** [comment] 2023-01-11 02:49
@kevinjohncutler Ope, my bad. It seems that using `cyto` fails, but `bact_omni` as a pre-trained model works just fine. If the former is deprecated that may resolve it.

I'm only trying CPU at the moment, but I can try GPU next!

**Comment by kevinjohncutler** [comment] 2023-01-11 02:55
@michaels10 Ah yes, the cellpose and omnipose models have different numbers of prediciton classes and therefore cannot be used as a basis for retraining each other. 

It looks like your label matrix is a different shape than your image too, so that would break training as well.

**Comment by michaels10** [comment] 2023-01-13 01:01
Huh -- it seems to be failing again. The failure occurs when I add testing data in addition to training data. With only training data, it works just fine. Another in our lab has recreated this issue, as well. Minimal set to reproduce below.
Command: 
`python -m cellpose --train --pretrained_model bact_omni --use_gpu --chan 0 --dir "/Users/michaelsandler/Documents/experiments/omnipose-test/examples/training" --test_dir "/Users/michaelsandler/Documents/experiments/omnipose-test/examples/testing" --n_epochs 100 --learning_rate 0.1`

(pls note -- am using cellpose because the fix in [the renaming bug](https://github.com/kevinjohncutler/omnipose/issues/30#issue-1507046383) did not work for me)
Exception:
```
Traceback (most recent call last):
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/__main__.py", line 506, in <module>
    main()
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/__main__.py", line 476, in main
    cpmodel_path = model.train(images, labels, train_files=image_names,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/models.py", line 1045, in train
    model_path = self._train_net(train_data, train_labels, 
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/core.py", line 1020, in _train_net
    imgi, lbl, scale = transforms.random_rotate_and_resize(
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/cellpose/transforms.py", line 839, in random_rotate_and_resize
    return omnipose.core.random_rotate_and_resize(X, Y=Y, scale_range=scale_range, gamma_range=gamma_range,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/omnipose/core.py", line 1511, in random_rotate_and_resize
    imgi[n], lbl[n], scale[n] = random_crop_warp(img, y, nt, tyx, nchan, scale[n], 
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/omnipose/core.py", line 1625, in random_crop_warp
    lbl[k] = do_warp(l, M, tyx, offset=offset, order=0, mode=mode) # order 0 is 'nearest neighbor'
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/omnipose/core.py", line 1739, in do_warp
    return scipy.ndimage.affine_transform(A, np.linalg.inv(M), offset=offset, 
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/scipy/ndimage/_interpolation.py", line 594, in affine_transform
    raise RuntimeError('affine matrix has wrong number of rows')
RuntimeError: affine matrix has wrong number of rows
```

Minimal set of images that causes this:
[example.zip](https://github.com/kevinjohncutler/omnipose/files/10407205/example.zip)

**Comment by kevinjohncutler** [comment] 2023-01-13 05:37
Hmm, probably an issue with using cellpose vs omnipose, bugs are bound to crop up there. That said, I have not ever used the test set feature during training, so that will be interesting to debug. First things first though, I need to solve this other issue with people not being able to isntall the development version.

**Comment by kevinjohncutler** [comment] 2023-01-19 07:02
Closing this because it was very likely just the dev version install issue.

**Closed by kevinjohncutler** 2023-01-19 07:02 UTC
